FROM python:3.11-slim

WORKDIR /app

# Copiar los archivos de requisitos
COPY requirements.txt .

# Instalar dependencias
RUN pip install --no-cache-dir -r requirements.txt

# Copiar el código de la aplicación
COPY . .

# Variables de entorno para conexión local
ENV DATABASE_URL=postgresql+psycopg://truc0:retrucovale4@postgres/trazaNet
ENV DEVELOPMENT_PROFILE=production
ENV MODEL_NAME=gpt-3.5-turbo

# Puerto en el que se ejecutará la aplicación
EXPOSE 3001

# Comando para iniciar la aplicación
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "3001", "--reload"] 