-- Crear tabla users si no existe
CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY,
  dicose VARCHAR(50) UNIQUE NOT NULL,
  email VARCHAR(255) UNIQUE NOT NULL,
  phone VARCHAR(20) NOT NULL,
  password VARCHAR(255) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  is_active BOOLEAN DEFAULT TRUE,
  is_admin BOOLEAN DEFAULT FALSE
);

-- Crear tabla animales si no existe
CREATE TABLE IF NOT EXISTS animales (
  id SERIAL PRIMARY KEY,
  dispositivo VARCHAR(50) UNIQUE NOT NULL,
  nombre_propietario VARCHAR(255) NOT NULL,
  edad_meses INTEGER NOT NULL,
  peso_kg DECIMAL(10, 2) NOT NULL,
  raza VARCHAR(100) NOT NULL,
  sexo VARCHAR(10) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
); 